# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HR/hKy5PRRwlu7EEv+qiFXpVxDpoD3A4SRVtb2WtNjF02BdfJam9i+h2m2dK5We7UR/LyMKU7WkG/Qoursvk4wv//phOOfyL/4uU7jxgWjXGiJsEJDXCbmCq2RZQrDXDzL429QiKIv3sGyLaZmMXNs9eAlMxsw3NrzMprzlJdhpPDcHUSNObe/VjBgK31xRM2Jh0nQ1m7tIBW4xvxNSevWqJEnYD/rUhF2i0R8HgfQKRwT2/6LzxFUQzGIIPplUVWw5i6vNvYDaWjjgmbwN1L/IadSXWc1/UTbByHVAec8UuyQ+mmm9H0yJfhDyPcIKpZjxxf545xDra7hmBAKFzTvpTcGJi0jleR7OJC4a7UQ1hXf/917ohgIuprEbe2TgYURVx6KU8/jFUOz6x7lbSu/KWongDS7Rz2NgCoQNOWllKYtAMkBzLBhUW/S/Agj89lB3fz3lb6dYB/0OwKEqhan2NClByNHFpJAEG6483fOdFRrZEZcHkSKpuoESszRYIX0QrcPHBybNOsxB4YA+iBKaseOFjxF8vx5embHcUZXrkoEYN0XS9OyB/eqrgiPF+/4sApzaILD3K5jKJq+ywcFUgwFc6Vkp4F8N13cFGpVRrMf40UVRhIDJotv2v2WPl6q9zdDWrOg2shzTdBQaxVwNP8rfrK6yHMzSahd1Xru4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
