appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HR/hKy5PRRwlu7EEv+qiFXpVxDpoD3A4SRVtb2WtNjF02BdfJam9i+h2m2dK5We7UR/LyMKU7WkG/Qoursvk4wv//phOOfyL/4uU7jxgWjXGiJsEJDXCbmCq2RZQrDXDzL429QiKIv3sGyLaZmMXNs9eAlMxsw3NrzMprzlJdhpPDcHUSNObe/VjBgK31xRM2Jh0nQ1m7tIBW4xvxNSevWqJEnYD/rUhF2i0R8HgfQKRwT2/6LzxFUQzGIIPplUVWw5i6vNvYDaWjjgmbwN1L/IadSXWc1/UTbByHVAec8UuyQ+mmm9H0yJfhDyPcIKpZjxxf545xDra7hmBAKFzTvpTcGJi0jleR7OJC4a7UQ1hXf/917ohgIuprEbe2TgYURVx6KU8/jFUOz6x7lbSu/KWongDS7Rz2NgCoQNOWllKYtAMkBzLBhUW/S/Agj89lB3fz3lb6dYB/0OwKEqhan2NClByNHFpJAEG6483fOdFRrZEZcHkSKpuoESszRYIX0QrcPHBybNOsxB4YA+iBKaseOFjxF8vx5embHcUZXrkoEYN0XS9OyB/eqrgiPF+/4sApzaILD3K5jKJq+ywcFUgwFc6Vkp4F8N13cFGpVRrMf40UVRhIDJotv2v2WPl6q9zdDWrOg2shzTdBQaxVwNP8rfrK6yHMzSahd1Xru4=}
